### PR TITLE
Form template

### PR DESCRIPTION
**Pull request by valadas**

### CODE REVIEW

**Comment by valadas** [comment]
@SCullman I am confused, Github shows I want to merge this into my repository, but I did nothing, did you submit this pull request to my repo?

**Comment by SCullman** [comment]
@valadas , nope, I only pushed to my repository in the FormTemplate branch. And this branch has been submitted as pull request to the DnnCommunity/fnl repository already in December 2016. All pushes to the same branch that happen afterwards are added to the initial pull request. 
I have no idea why my push to that branch today also triggers actions to your repository.
Please note that I have no permissions for DnnCommunity/fnl.

**Comment by valadas** [comment]
Oh, I think it is because we both have open pull requests that cannot be both auto-merged on the same repository, so it notifies that my pull request will need to be handled manually...

**Comment by valadas** [comment]
@SCullman I asked Ernst Peter Tamminga to merge your pull request in the DnnCommunity github and it is done. I tried it on Dnn 9.1.1 and 9.2 and it works good, so I am going to close this pull request here. Thanks.

**Pull request closed without merging**
